In [15]:
import pandas as pd 
import warnings

In [16]:
df=pd.read_csv(r"C:\Users\kartik chauhan\Downloads\bank_loan_default_raw.csv")
df.head()

,customer_id,age,gender,marital_status,employment_type,monthly_income,credit_score,loan_amount,loan_type,loan_term_months,existing_loans,num_dependents,application_date,late_payments_last_year,debt_to_income_ratio,home_ownership,default
0,LOAN04622,47,female,single,salaried,25434.0,660.0,414595.0,personal loan,60,1,4.0,2023/06/16,1,21.44,mortgaged,no
1,LOAN00589,37,Male,Married,Salaried,46509.0,558.0,123844.0,Home Loan,120,2,2.0,11-04-2025,1,5.40,Rented,N
2,LOAN02802,26,male,single,salaried,26971.0,675.0,242076.0,auto loan,180,1,2.0,2024/10/13,2,6.11,owned,No
3,LOAN04355,55,Male,Divorced,Salaried,55862.0,667.0,549667.0,Home Loan,48,2,1.0,05/14/2023,1,5.12,Mortgaged,No
4,LOAN04284,59,Female,Single,Business Owner,124570.0,708.0,556215.0,Personal Loan,60,3,3.0,16 Jan 2025,0,13.73,Mortgaged,No

In [17]:
df.shape

(5040, 17)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5040 entries, 0 to 5039
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              5040 non-null   object
 1   age                      5040 non-null   int64
 2   gender                   5040 non-null   object
 3   marital_status           5040 non-null   object
 4   employment_type          5040 non-null   object
 5   monthly_income           4838 non-null   float64
 6   credit_score             4840 non-null   float64
 7   loan_amount              5040 non-null   float64
 8   loan_type                5040 non-null   object
 9   loan_term_months         5040 non-null   int64
 10  existing_loans           5040 non-null   int64
 11  num_dependents           4837 non-null   float64
 12  application_date         5040 non-null   object
 13  late_payments_last_year  5040 non-null   int64
 14  debt_to_income_ratio     4839 non-null   float64
 15  home_ownership           4839 non-null   object
 16  default                  5040 non-null   object
dtypes: float64(5), int64(4), object(8)
memory usage: 669.5+ KB

In [19]:
df.isnull().sum()

customer_id                  0
age                          0
gender                       0
marital_status               0
employment_type              0
monthly_income             202
credit_score               200
loan_amount                  0
loan_type                    0
loan_term_months             0
existing_loans               0
num_dependents             203
application_date             0
late_payments_last_year      0
debt_to_income_ratio       201
home_ownership             201
default                      0
dtype: int64

In [20]:
# remove duplicate rows
print("Before:", df.shape)
df = df.drop_duplicates(subset='customer_id')
print("After:", df.shape)

Before: (5040, 17)
After: (5000, 17)

In [21]:
# fic the nagetive age
df['age'] = df['age'].abs()

In [22]:
# categorical column case fix
cat_cols = ['gender', 'marital_status', 'employment_type', 'loan_type', 'home_ownership', 'default']

for col in cat_cols:
    df[col] = df[col].astype(str).str.strip().str.lower()

df['gender'].unique()

array(['female', 'male'], dtype=object)

In [23]:
# standerize default column
df['default'] = df['default'].replace({'y': 'yes', 'n': 'no'})
df['default'] = df['default'].str.capitalize() 
df['default'].value_counts()

default
No     3025
Yes    1975
Name: count, dtype: int64

In [24]:
# set date format
df['application_date'] = pd.to_datetime(df['application_date'], format='mixed', dayfirst=False)
df['application_date'].head(10)

0   2023-06-16
1   2025-11-04
2   2024-10-13
3   2023-05-14
4   2025-01-16
5   2024-01-06
6   2023-03-16
7   2023-05-01
8   2023-06-12
9   2024-02-25
Name: application_date, dtype: datetime64[ns]

In [26]:
# fill the missing values
# Numeric columns
for col in ['monthly_income', 'credit_score', 'debt_to_income_ratio', 'num_dependents']:
    df[col] = df[col].fillna(df[col].median())

# Categorical 
df['home_ownership'] = df['home_ownership'].fillna('unknown')

df.isnull().sum()

customer_id                0
age                        0
gender                     0
marital_status             0
employment_type            0
monthly_income             0
credit_score               0
loan_amount                0
loan_type                  0
loan_term_months           0
existing_loans             0
num_dependents             0
application_date           0
late_payments_last_year    0
debt_to_income_ratio       0
home_ownership             0
default                    0
dtype: int64

In [28]:
df['loan_amount'].describe()

df[df['loan_amount'] > df['loan_amount'].quantile(0.99)]

,customer_id,age,gender,marital_status,employment_type,monthly_income,credit_score,loan_amount,loan_type,loan_term_months,existing_loans,num_dependents,application_date,late_payments_last_year,debt_to_income_ratio,home_ownership,default
241,LOAN01431,45,female,married,self-employed,63771.0,519.0,684795.0,personal loan,84,1,0.0,2025-02-01,0,10.16,nan,Yes
264,LOAN01189,34,female,married,salaried,47638.0,702.0,838302.0,education loan,36,0,0.0,2025-12-03,0,50.41,owned,Yes
350,LOAN01338,37,male,divorced,self-employed,58553.0,617.0,714963.0,personal loan,240,0,0.0,2023-08-28,1,4.72,rented,No
377,LOAN04311,48,female,married,salaried,28408.0,638.0,3591310.0,education loan,180,2,1.0,2025-03-06,0,4.00,mortgaged,No
446,LOAN03861,41,male,married,business owner,129570.0,719.0,779273.0,home loan,36,1,2.0,2023-10-20,1,21.57,owned,No
473,LOAN04630,36,female,single,salaried,57638.0,536.0,671766.0,home loan,180,0,0.0,2025-05-25,0,11.04,owned,No
533,LOAN00132,47,female,divorced,self-employed,5000.0,648.0,3492680.0,home loan,24,2,4.0,2023-09-04,0,150.00,mortgaged,Yes
604,LOAN04062,54,male,married,salaried,63888.0,638.0,660911.0,home loan,36,0,0.0,2024-06-01,0,33.73,mortgaged,No
605,LOAN02202,43,male,single,self-employed,30631.0,575.0,657224.0,home loan,24,1,1.0,2024-09-02,1,96.79,owned,Yes
803,LOAN01537,26,male,single,salaried,31010.0,678.0,654689.0,personal loan,180,1,2.0,2024-02-23,1,12.63,rented,No
1067,LOAN04993,63,male,single,salaried,45842.0,626.0,688504.0,education loan,36,1,0.0,2023-12-18,0,38.46,rented,Yes
1138,LOAN00134,35,male,divorced,salaried,48720.0,652.0,4030180.0,home loan,120,0,3.0,2024-09-12,1,11.61,owned,Yes
1205,LOAN04367,50,female,married,self-employed,27760.0,545.0,687887.0,personal loan,84,3,1.0,2023-10-22,0,35.04,owned,Yes
1388,LOAN02448,44,male,married,unemployed,11702.0,619.0,675093.0,home loan,180,0,1.0,2024-09-05,1,24.38,owned,Yes
1452,LOAN02928,39,male,married,business owner,76622.0,667.0,890775.0,education loan,48,1,0.0,2023-07-18,2,19.17,rented,No
1565,LOAN00135,35,female,single,salaried,21740.0,654.0,670289.0,personal loan,120,2,2.0,2023-07-12,0,23.61,rented,Yes
1593,LOAN03154,31,male,married,salaried,55837.0,639.0,774363.0,education loan,84,1,0.0,2025-04-13,1,12.05,mortgaged,No
1756,LOAN01417,33,male,married,salaried,40028.0,824.0,674864.0,education loan,48,0,0.0,2023-11-07,0,32.95,rented,No
1947,LOAN03683,48,male,married,salaried,38001.0,634.0,760005.0,home loan,180,2,1.0,2024-12-14,0,9.20,mortgaged,No
2056,LOAN00382,45,male,single,salaried,40240.0,614.0,695370.0,auto loan,60,1,1.0,2023-01-27,0,36.73,rented,Yes
2061,LOAN03202,33,male,married,unemployed,5000.0,762.0,718699.0,education loan,60,0,1.0,2023-08-24,1,150.00,rented,Yes
2140,LOAN04339,45,male,married,self-employed,23357.0,719.0,688722.0,personal loan,36,1,2.0,2025-04-23,0,88.00,rented,No
2141,LOAN02671,53,male,married,salaried,34257.0,648.0,688249.0,home loan,12,1,2.0,2024-04-28,0,150.00,rented,Yes
2205,LOAN02586,36,female,married,self-employed,57783.0,661.0,681879.0,education loan,84,2,0.0,2025-02-15,1,14.29,owned,No
2267,LOAN04542,36,female,single,self-employed,48855.0,750.0,671413.0,auto loan,84,0,3.0,2023-06-14,0,21.26,mortgaged,Yes
2368,LOAN01660,23,female,married,unemployed,17434.0,648.0,699274.0,home loan,180,0,1.0,2023-07-25,0,32.50,rented,Yes
2549,LOAN01754,62,female,single,salaried,25329.0,696.0,669931.0,home loan,180,2,0.0,2025-04-10,1,22.15,mortgaged,No
2581,LOAN02179,29,female,married,salaried,58418.0,548.0,1971800.0,home loan,240,2,1.0,2023-09-17,1,1.00,rented,No
2591,LOAN04553,35,male,single,salaried,42770.0,699.0,722066.0,personal loan,12,2,1.0,2024-06-29,1,123.25,rented,Yes
2631,LOAN00995,37,male,married,salaried,37490.0,694.0,3011430.0,business loan,120,0,2.0,2025-05-04,0,5.18,rented,No
2776,LOAN00205,22,male,divorced,salaried,11111.0,630.0,885420.0,personal loan,60,0,0.0,2024-03-07,0,135.32,rented,Yes
2908,LOAN03069,29,male,married,self-employed,69408.0,789.0,705420.0,auto loan,60,1,1.0,2024-02-04,0,12.05,rented,No
3003,LOAN01340,32,male,married,salaried,51288.0,678.0,738199.0,business loan,12,1,2.0,2024-04-24,1,121.52,mortgaged,Yes
3126,LOAN04983,28,female,married,salaried,42446.0,698.0,723195.0,auto loan,36,0,1.0,2024-08-20,0,45.30,rented,Yes
3136,LOAN03679,46,male,divorced,salaried,59905.0,549.0,810411.0,home loan,48,1,3.0,2025-01-24,2,32.78,rented,Yes
3374,LOAN01864,59,male,married,salaried,16173.0,519.0,673188.0,auto loan,24,1,0.0,2023-12-02,0,150.00,mortgaged,Yes
3411,LOAN01780,23,male,married,self-employed,35103.0,705.0,694904.0,personal loan,240,1,4.0,2023-06-23,2,1.00,mortgaged,Yes
3460,LOAN01010,53,male,married,salaried,50196.0,710.0,739669.0,personal loan,36,2,3.0,2023-06-28,2,42.52,rented,Yes
3765,LOAN00386,26,male,married,salaried,68269.0,656.0,1795750.0,home loan,12,1,2.0,2024-04-21,3,11.30,rented,No
3950,LOAN03737,25,male,single,unemployed,5000.0,777.0,812029.0,personal loan,180,0,3.0,2023-09-18,1,88.42,rented,Yes
3999,LOAN02248,52,male,divorced,self-employed,67754.0,597.0,670888.0,auto loan,24,0,1.0,2025-04-08,0,43.73,rented,Yes
4078,LOAN03750,62,female,married,salaried,34905.0,639.0,670007.0,home loan,120,2,1.0,2024-09-13,2,11.28,mortgaged,No
4081,LOAN03157,33,female,single,salaried,42770.0,590.0,665532.0,business loan,24,0,2.0,2024-04-07,2,57.94,owned,No
4123,LOAN02079,38,female,married,salaried,39611.0,691.0,672536.0,home loan,120,1,0.0,2024-05-26,0,17.14,mortgaged,No
4202,LOAN04608,60,male,single,self-employed,39936.0,711.0,669294.0,personal loan,120,0,0.0,2025-05-23,1,13.31,rented,Yes
4204,LOAN03519,52,female,married,unemployed,20615.0,617.0,657448.0,home loan,120,1,2.0,2023-10-16,1,24.42,owned,Yes
4205,LOAN00734,43,male,married,business owner,48108.0,595.0,2486770.0,auto loan,12,0,0.0,2024-01-09,1,40.08,owned,No
4616,LOAN00827,44,male,married,salaried,48436.0,643.0,2879130.0,home loan,240,1,2.0,2024-03-30,1,1.00,rented,No
4639,LOAN01944,21,female,married,salaried,43161.0,573.0,737260.0,education loan,60,1,1.0,2023-05-30,0,28.00,mortgaged,Yes
4876,LOAN03371,48,female,single,salaried,42309.0,663.0,735956.0,home loan,240,2,2.0,2023-01-09,0,13.34,rented,No

In [29]:
df.info()
df.head()
df.to_csv('bank_loan_cleaned.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 0 to 5039
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              5000 non-null   object
 1   age                      5000 non-null   int64
 2   gender                   5000 non-null   object
 3   marital_status           5000 non-null   object
 4   employment_type          5000 non-null   object
 5   monthly_income           5000 non-null   float64
 6   credit_score             5000 non-null   float64
 7   loan_amount              5000 non-null   float64
 8   loan_type                5000 non-null   object
 9   loan_term_months         5000 non-null   int64
 10  existing_loans           5000 non-null   int64
 11  num_dependents           5000 non-null   float64
 12  application_date         5000 non-null   datetime64[ns]
 13  late_payments_last_year  5000 non-null   int64
 14  debt_to_income_ratio     5000 non-null   float64
 15  home_ownership           5000 non-null   object
 16  default                  5000 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(4), object(7)
memory usage: 703.1+ KB